### ISSUE TITLE
Now it doesn't work

### ISSUE THREAD

**Issue by muezis** [JoshLmao/Genify#5]
I don't know if you know that. But just in case, I decided to let you know. Now it absolutely doesn't work. I click Sign In, but nothing happens :c
https://imgur.com/a/7U4cguf

**Comment by JoshLmao** [comment]
Thanks for bringing this up. I thought this problem was fixed but apparently not. Reason is because the cookies aren't getting deleted correctly. 

As a workaround for now, delete the "spotify-auth" cookie to fix it. In Chrome, click the lock icon next to the url and then "Cookies (x in use)", then follow this

![image](https://user-images.githubusercontent.com/22716832/87455856-fd94b300-c5fd-11ea-9e4b-b11cc7290a16.png)

**Comment by muezis** [comment]
Yes, it helped

**Comment by JoshLmao** [comment]
Should be fixed with v3.0.1 (105d383ddd1bc53c0158536b55d6badfb23d6f28). Thanks for reporting
