### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by muezis** [JoshLmao/Genify#6]
Yep, it's me. Again :D

Everything is perfect. But there are three small bugs that you might want to fix)

1. Constantly resets the authorization. I don't know how long it takes, but I think 1-2 hours. And even if the browser tab wasn't closed, this message appears. https://imgur.com/a/UokA3gw Then you need to refresh the page and click "Sign In" again. I use different sites with the Spotify API. And there authorization is never reset at all. I only logged in once.

2. Delay. The text appears after 6-15 seconds. Although I have a good Internet connection, about 90-100mbps

3. White screen if a local track plays. https://imgur.com/a/nlfQ8HI Then, when I turn on a track from Spotify - there will still be a white screen until the page refresh.

Anyway, thanks a lot for integrating the player, and all these things aren't really that important)

**Comment by JoshLmao** [comment]
Hey. Thanks for these, I appreciate it. By the way, I have [a project board](https://github.com/JoshLmao/Genify/projects/1) to keep track of what to work on, if you're interested. 

1. Unfortunately, this is a limitation of what is being used. The site is server-less which eliminates most methods that allow me to refresh it without asking users to sign in again. However, there is this new [Authorization Code Flow with Proof Key for Code Exchange (PKCE)](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce) which I'll look into since that allows me to refresh without asking and without a server

2. I'm aware that it takes a little to gather lyrics. Since I rushed to rework the site, I used the same algorithm to retrieve lyrics. This is low priority **for now ** but I will get around to it

3. That's a nice find! I completely forgot Spotify allowed for playing of local files. I'll look into that one and make it work#

**Comment by JoshLmao** [comment]
I've fixed it now so it won't crash when playing local files and I've implemented the PKCE auth flow so now you only need to authorize once. Thanks for the suggestion.

I've added a note to improve the playback of local files in my To Do list so i'll come back to that soon, as well as the lyrics being slow issue.

**Comment by muezis** [comment]
Wow, now I have lyrics even for local tracks. I didn't even hope for that. It's not available on any other site. Really cool)
