### ISSUE TITLE
White screen blocking

### ISSUE THREAD

**Issue by muezis** [JoshLmao/Genify#8]
Hi. If I don't play music in Spotify about hour, but Spotify is open (your site also open), a white screen appears there, and even when I start playing music, I need to refresh page to remove the white screen. 

https://imgur.com/a/MZeJuFr

Yes, it's nothing, it's not difficult to press one button, and probably not worth the time to fix it, just decided to report it)

**Comment by muezis** [comment]
By the way, the player buttons on your site stops working even earlier, about 10 minutes after stops playing.

**Comment by muezis** [comment]
Hmm. Interesting. If I enable private mode in Spotify, your site will always have a white screen, and even refresh the page will not help. But why the white screen turn on due to inactivity...

**Comment by JoshLmao** [comment]
The white screen appearing seems to be what happens when a crash/error happens, since that's what happened with one of your problems in #6. I also wanna say that since I just rewrote the site, there will be a lot of errors like this so thank you for finding and reporting them 🙇‍♂️

Your first two comments seem tied to the auth not being refreshed correctly and updated, and your latest one seems to be private mode blocking cookies, since auth is stored there. When i get some time, I'll look into them

**Comment by JoshLmao** [comment]
I've implemented a fix for this and is in v3.0.3. From what I can tell, the issue doesn't seem to happen anymore so I will close it. If it does happen, just reopen it 😉
